* initial results

thunder 07:12:11 iris> lein with-profile dev test iris.perf-test
(216 cubes  no parallelism) : "Elapsed time: 8776.367902 msecs"
^C

What? this is 1/2 the speed of normal.

thunder 07:11:18 iris> lein test iris.perf-test
(216 cubes  no parallelism) : "Elapsed time: 14606.117784 msecs"

lein docs say :default is a composite profile with
[:base :system :user :provided :dev].

thunder 07:14:15 iris> lein with-profile base test iris.perf-test
(216 cubes  no parallelism) : "Elapsed time: 14466.744698 msecs"
thunder 07:16:01 iris> lein with-profile system test iris.perf-test
(216 cubes  no parallelism) : "Elapsed time: 8582.240867 msecs"
thunder 07:16:27 iris> lein with-profile user test iris.perf-test
(216 cubes  no parallelism) : "Elapsed time: 8917.121893 msecs"
thunder 07:16:55 iris> lein with-profile provided test iris.perf-test
(216 cubes  no parallelism) : "Elapsed time: 8702.617338 msecs"

Okay, what is different between :base and the rest?

> lein show-profiles base
{:resource-paths ["dev-resources"],
 :jvm-opts
 ["-XX:+TieredCompilation"
  "-XX:TieredStopAtLevel=1"
  "-XX:-OmitStackTraceInFastThrow"],
...

Well, now I understand wtf TierCompilation is!  UGH!

https://github.com/technomancy/leiningen/wiki/Faster

Leiningen 2.1.0 onward get a speed boost by disabling the optimized
compilation (which only benefits long-running processes) for both your
project and Leiningen itself.

Be aware that this can negatively affect performance in the long run
(or lead to inaccurate benchmarking results). If you do have a
long-running processes and want the JVM to fully optimize, you can
disable tiered compilation by ...

Okay, added that to project.clj...

* new results

Nice 2x speed boost!

thunder 07:22:46 iris> lein test iris.perf-test

lein test iris.perf-test
(216 cubes  no parallelism) : "Elapsed time: 8592.009211 msecs"
(216 cubes  2x parallelism) : "Elapsed time: 4292.005445 msecs"
(216 cubes  3x parallelism) : "Elapsed time: 3248.854562 msecs"
(216 cubes  4x parallelism) : "Elapsed time: 3264.126976 msecs"
(216 cubes  6x parallelism) : "Elapsed time: 2741.459156 msecs"
(216 cubes  8x parallelism) : "Elapsed time: 2304.194795 msecs"
(216 cubes 12x parallelism) : "Elapsed time: 2590.118084 msecs"
(216 cubes 16x parallelism) : "Elapsed time: 2815.603783 msecs"
(216 cubes 24x parallelism) : "Elapsed time: 3487.783907 msecs"
(216 cubes 32x parallelism) : "Elapsed time: 3905.204436 msecs"
(single fullscreen triangle  no parallelism) : "Elapsed time: 4882.02033 msecs"
(single fullscreen triangle  2x parallelism) : "Elapsed time: 2651.232392 msecs"
(single fullscreen triangle  3x parallelism) : "Elapsed time: 2061.476135 msecs"
(single fullscreen triangle  4x parallelism) : "Elapsed time: 1860.74629 msecs"
(single fullscreen triangle  6x parallelism) : "Elapsed time: 1473.644829 msecs"
(single fullscreen triangle  8x parallelism) : "Elapsed time: 1309.661062 msecs"
(single fullscreen triangle 12x parallelism) : "Elapsed time: 1972.506385 msecs"
(single fullscreen triangle 16x parallelism) : "Elapsed time: 1619.04987 msecs"
(single fullscreen triangle 24x parallelism) : "Elapsed time: 1844.076739 msecs"
(single fullscreen triangle 32x parallelism) : "Elapsed time: 2039.124112 msecs"

Ran 21 tests containing 20 assertions.
0 failures, 0 errors.

* old results for comparison

lein test iris.perf-test
(216 cubes  no parallelism) : "Elapsed time: 14795.149657 msecs"
(216 cubes  2x parallelism) : "Elapsed time: 8491.273422 msecs"
(216 cubes  3x parallelism) : "Elapsed time: 6398.070178 msecs"
(216 cubes  4x parallelism) : "Elapsed time: 5828.502012 msecs"
(216 cubes  6x parallelism) : "Elapsed time: 5170.583644 msecs"
(216 cubes  8x parallelism) : "Elapsed time: 5038.825765 msecs"
(216 cubes 12x parallelism) : "Elapsed time: 5350.82897 msecs"
(216 cubes 16x parallelism) : "Elapsed time: 5928.403589 msecs"
(216 cubes 24x parallelism) : "Elapsed time: 7249.863398 msecs"
(216 cubes 32x parallelism) : "Elapsed time: 8401.258671 msecs"
(single fullscreen triangle  no parallelism) : "Elapsed time: 9169.407479 msecs"
(single fullscreen triangle  2x parallelism) : "Elapsed time: 5362.604465 msecs"
(single fullscreen triangle  3x parallelism) : "Elapsed time: 4032.685349 msecs"
(single fullscreen triangle  4x parallelism) : "Elapsed time: 3573.987153 msecs"
(single fullscreen triangle  6x parallelism) : "Elapsed time: 3118.119322 msecs"
(single fullscreen triangle  8x parallelism) : "Elapsed time: 3002.58433 msecs"
(single fullscreen triangle 12x parallelism) : "Elapsed time: 3908.954978 msecs"
(single fullscreen triangle 16x parallelism) : "Elapsed time: 4566.061129 msecs"
(single fullscreen triangle 24x parallelism) : "Elapsed time: 4649.887223 msecs"
(single fullscreen triangle 32x parallelism) : "Elapsed time: 5423.851433 msecs"
